package com.hris.main.model.generic;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 *
 * @author Maikel Chandika <mkdika@gmail.com>
 * 
 * This is use for common table that need to be recorded transaction trail
 * histories. or Can be generated by Approval System.
 */
public interface DataTrail{
    
    Object getId();
            
    @JsonIgnore
    default String getTrailRemarks() {
        return "Remark not available.";
    }
    
    @JsonIgnore
    default String getApprovalTitle() {
        return "Approval title not implemented yet.";
    }
}
